Error out if SSH fails
I think this will stop it incorrectly deleting all snapshots and causing replication to be restarted from scratch

diff --git a/zxfer b/zxfer
--- a/zxfer
+++ b/zxfer
@@ -442,7 +442,7 @@ copy_snap() {
             sed "s#%%title%%#$copysrc#g" )
           $LZFS send -i "$copyprev" "$copysrc" | dd obs=1m | dd bs=1m | \
             $PROGRESS_DIALOG | $RZFS receive $option_F "$copydest" || \
-            { echo "Error when zfs send/receiving."; beep; exit 1; }        
+            { echo "Error when zfs send/receiving."; beep; exit 1; }
         else
           SIZE_DATASET=$( $LZFS send -nPv -i "$copyprev" "$copysrc" 2>&1 ) ||
             { echo "Error calculating estimate: $SIZE_DATASET"; beep; exit 1; }
@@ -673,8 +673,10 @@ get_zfs_list() {
   # Above replaced by shell expansion to avoid forking
   initial_source=${initial_source%/}
 
-  rzfs_list_ho_s=$($RZFS list -t filesystem,volume -Ho name -s creation)
-  lzfs_list_hr_s_snap=$($LZFS list -Hr -o name -s creation -t snapshot)
+  rzfs_list_ho_s=$($RZFS list -t filesystem,volume -Ho name -s creation) ||
+    { echo "Failed to retrieve datasets from the destination"; exit 2 }
+  lzfs_list_hr_s_snap=$($LZFS list -Hr -o name -s creation -t snapshot) ||
+    { echo "Failed to retrieve snapshots from the source"; exit 2 }
   # Note that for OpenSolaris compatibility, instead of using gtac
   # we will use ...| cat -n | sort -nr | cut -c 8-
   # gtac line
@@ -683,11 +685,14 @@ get_zfs_list() {
   if [ "$RZFS" = "$LZFS" ]; then
     rzfs_list_hr_S_snap=$lzfs_list_hr_S_snap
   else
-    rzfs_list_hr_S_snap=$($RZFS list -Hr -o name -S creation -t snapshot)
+    rzfs_list_hr_S_snap=$($RZFS list -Hr -o name -S creation -t snapshot) ||
+      { echo "Failed to retrieve snapshots from the destination"; exit 2 }
   fi
 
-  recursive_source_list=$($LZFS list -t filesystem,volume -Hr -o name "$initial_source")
-  recursive_dest_list=$($RZFS list -t filesystem,volume -Hr -o name "$destination")
+  recursive_source_list=$($LZFS list -t filesystem,volume -Hr -o name "$initial_source") ||
+    { echo "Failed to retrieve list of datasets from the source"; exit 2 }
+  recursive_dest_list=$($RZFS list -t filesystem,volume -Hr -o name "$destination") ||
+    { echo "Failed to retrieve list of datasets from the destination"; exit 2 }
 
   # Exit if source not sound
   if [ "$recursive_source_list" = "" ]; then
